### ISSUE TITLE
Allow input for registering custom rules

### ISSUE THREAD

**Issue by mitchspano** [mitchspano/sfdx-scan-pull-request#14]
When using a PMD ruleset file which contains a custom rule, sfdx scanner requires the registration of the rules before they can be picked up by the scan. For each file, we need to call `sfdx scanner:rule:add` with the appropriate `--language` and `--path` arguments.

The [sfdx-scan-pull-request](https://github.com/mitchspano/sfdx-scan-pull-request) action should enable users to define the languages and paths that they want to register before scan execution.

For additional context, see [this comment](https://github.com/forcedotcom/sfdx-scanner/issues/571#issuecomment-1033987744).

**Comment by mitchspano** [comment]
I've began working on this in the [`feature/registerCustomRules` branch](https://github.com/mitchspano/sfdx-scan-pull-request/tree/feature/registerCustomRules).

We can test it out like this:

```yml
- name: Run SFDX Scanner - Report findings as comments
  uses: mitchspano/sfdx-scan-pull-request@feature/registerCustomRules
  with:
    report-mode: comments
    pmdconfig: "pmd/category/xml/custom.xml"
    custom-pmd-rules: '[{ "rulesetPath": "pmd/category/xml/custom.xml", "language": "xml"}]'
  env:
    GITHUB_TOKEN: ${{ secrets.TOKEN }}
```
