### ISSUE TITLE
Line must be part of the diff error

### ISSUE THREAD

**Issue by dawidleb** [mitchspano/sfdx-scan-pull-request#16]
Scanner tries to comment the lines which are not part of the diff, and the action fails:

 ```
data: {
      message: 'Validation Failed',
      errors: [
        {
          resource: 'PullRequestReviewComment',
          code: 'custom',
          field: 'pull_request_review_thread.line',
          message: 'pull_request_review_thread.line must be part of the diff'
        },
        {
          resource: 'PullRequestReviewComment',
          code: 'custom',
          field: 'pull_request_review_thread.start_line',
          message: 'pull_request_review_thread.start_line must be part of the same hunk as the line.'
        },
        {
          resource: 'PullRequestReviewComment',
          code: 'missing_field',
          field: 'pull_request_review_thread.diff_hunk'
        }
      ],
      documentation_url: 'https://docs.github.com/rest'
    }
  },
```

Scanner actions:
 ```
           - name: 'Install Salesforce CLI and Scanner'
              run: |
                  npm install sfdx-cli
                  node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner
                  
            - name: SFDX Scan Pull Request
              uses: mitchspano/sfdx-scan-pull-request@v0.1.1
              with:
                severity-threshold: 4
                strictly-enforced-rules: '[{ "engine": "pmd", "category": "Design,Best Practices,Performance"}]'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

For example: 
1. there is a long class in a main branch, let's say 50 lines of the code, which was added to this branch before using scanner in a pipeline
2. you add a small change in a middle of the class, let's say in a line 30
3. scanner tries to add a comment to line 2, but it is not part of the diff, so it fails.
