### ISSUE TITLE
How to make the action use multiple rulesets

### ISSUE THREAD

**Issue by rsoesemann** [mitchspano/sfdx-scan-pull-request#34]
[According to Salesforce ](https://github.com/forcedotcom/sfdx-scanner/issues/571)you have to split custom ruleset into multiple files per language to make it work on Custom XPath Rules.

How would I need to change this Action

https://github.com/rsoesemann/unhappy-soup/blob/master/.github/workflows/main.yml

to make use of the XML and Apex rulesets in

https://github.com/rsoesemann/unhappy-soup/tree/master/pmd/category

I made it work in a Bitbucket Pipeline using multiple files and multiple add commands.
<img width="1013" alt="Screenshot 2023-03-18 at 11 04 58" src="https://user-images.githubusercontent.com/8180281/226099047-151f55ec-6ea0-4fea-8965-b5f44e2ef269.png">

**Comment by mitchspano** [comment]
Duplicate of #14

**Comment by mitchspano** [comment]
When looking at the [PMD Documentation](https://docs.pmd-code.org/latest/pmd_userdocs_cli_reference.html), it says:
```
--rulesets <refs>
-R <refs>

Required Path to a ruleset xml file. The path may reference a resource on the classpath of the application, be a local file system path, or a URL. The option can be repeated, and **multiple arguments separated by comma can be provided to a single occurrence of the option**.
```

I would imagine that the scanner is simply passing the CLI args to PMD - so the PMD documentation leads me to believe that comma separated paths to multiple ruleset files *should* be sufficient.

**Comment by rsoesemann** [comment]
Did you make that work?

**Comment by mitchspano** [comment]
So I did some investigation, and it seems like the scanner doesn't support the comma separated inputs.

However, you can compose your ruleset files into a master ruleset and reference the top level file:

```
.
├── MyClass.cls
├── YourClass.cls
├── masterRuleset.xml
├── ruleset1.xml
└── ruleset2.xml
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="master"
    xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
    <description>Master Ruleset</description>
    <rule ref="ruleset1.xml" />
    <rule ref="ruleset2.xml" />
</ruleset>
```
```yml
- name: Run SFDX Scanner - Report findings as comments
uses: mitchspano/sfdx-scan-pull-request@v0.1.11
with:
  pmdconfig: masterRuleset.xml
  severity-threshold: 3
  strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
```

This will allow you to partition your rules into multiple files and reference all of the rulesets when using this action!
