### ISSUE TITLE
Scan fails with version @v0.1.8

### ISSUE THREAD

**Issue by jbatt08** [mitchspano/sfdx-scan-pull-request#39]
The scanner is failing after starting to use [v0.1.8](https://github.com/mitchspano/sfdx-scan-pull-request/releases/tag/v0.1.8).

Here's the log:

```
Beginning sfdx-scan-pull-request run...
Validating that this action was invoked from an acceptable context...
Getting difference within the pull request ... [ 'dev-uat', 'feature/CSE-1255-GuardrilesToPreventOverAllotment-PR2' ]
Getting existing comments using GitHub REST API...
(node:1956) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Performing static code analysis on all of the files in the difference...
node:internal/errors:841
  const err = new Error(message);
              ^

Error: Command failed: npx sfdx scanner:run --pmdconfig ruleset.xml --target force-app/main/default/classes/CSLeadsRESTControllerV2.cls --json
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/main/dist/index.js:1:[7](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:8)[8](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:9)66
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/main/dist/index.js:1:7631
    at new Promise (<anonymous>)
    at o (/home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/main/dist/index.js:1:7378)
    at cli (/home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/main/dist/index.js:1:774[9](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:10))
    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/main/dist/index.js:1:8087 {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(2670) [Uint8Array] [
      123,  [10](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:11),  32,  32,  34, [11](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:12)5, 116,  97, 116, 117, 115,  34,
       58,  32,  49,  44,  10,  32,  32,  34, 110,  97, 109, 101,
       34,  58,  32,  34,  34,  44,  10,  32,  32,  34, 109, 101,
      115, 115,  97, 103, 101,  34,  58,  32,  34,  85, 110, 101,
      [12](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:13)0, 112, 101,  99, 116, 101, 100,  32,  97, 1[14](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:15), 103, 117,
      109, 101, 110, 116,  58,  32,  76,  97, 121, 111, 117, 116,
       46, 108,  97, 121, 111, 117, 116,  45, 109, 101, 116,  97,
       46, 120, 109, 108,  44, 102, 111, 114,  99, 101,  45,  97,
      112, 112,  47, 109,
      ... 2570 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 1989,
  stdout: Buffer(2670) [Uint8Array] [
    123,  10,  32,  32,  34, 1[15](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:16), 1[16](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:17),  97, 116, 1[17](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:18), 115,  34,
     58,  32,  49,  44,  10,  32,  32,  34, 110,  97, 109, 101,
     34,  58,  32,  34,  34,  44,  10,  32,  32,  34, 109, 101,
    115, 115,  97, 103, 101,  34,  58,  32,  34,  85, 110, 101,
    1[20](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:21), 112, 101,  99, 116, 101, 100,  32,  97, 114, 103, 117,
    109, 101, 110, 116,  58,  32,  76,  97, 1[21](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:22), 111, 117, 116,
     46, 108,  97, 121, 111, 117, 116,  45, 109, 101, 116,  97,
     46, 120, 109, 108,  44, 102, 111, 114,  99, 101,  45,  97,
    112, 112,  47, 109,
    ... [25](https://github.com/BlueWaveFinanceGroup/SMP/actions/runs/4467577726/jobs/7847218088?pr=5127#step:4:26)70 more items
  ],
  stderr: Buffer(0) [Uint8Array] []
}
```

Here's our yaml:
```
name: Static Analysis
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner
      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@main
        with:
          pmdconfig: ruleset.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Running this command locally didn't produce any errors:

` sfdx scanner:run --pmdconfig ruleset.xml --target force-app/main/default/classes/CSLeadsRESTControllerV2.cls

`

And after reverting to v0.1.7, the scanner is working.

**Comment by mitchspano** [comment]
Thanks for raising this issue @jbatt08. We have experienced a similar issue yesterday and thought it was related to the concatenation of the target path. Your ability to run locally is interesting and makes me  reconsider the target path hypothesis.

I will take a look at this issue and let you know what I find. For now, please continue with v0.1.7.

Thanks,
-Mitch

**Comment by mitchspano** [comment]
Hey @jbatt08, would you be able to try executing the action using `npx` instead of `node_modules`?

```yml
- name: Install SFDX CLI and Scanner
  run: |
    npm install sfdx-cli
    node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner
```
=>
```
- name: Install SFDX CLI and Scanner
  run: |
    npm install sfdx-cli
    npx sfdx plugins:install @salesforce/sfdx-scanner
```
I believe this could be the cause of this issue. Let me know what you find.

Thanks!
