### ISSUE TITLE
Error while using the action

### ISSUE THREAD

**Issue by devboorla** [mitchspano/sfdx-scan-pull-request#50]
Beginning sfdx-scan-pull-request run...
Validating that this action was invoked from an acceptable context...
Getting difference within the pull request ... { baseRef: 'abc-demo-01', headRef: 'jira-001' }
error: remote destination already exists.
(node:[14](https://github.ABC.com/salesforce/ABC-Salesforce-POC/actions/runs/84541/jobs/88035#step:9:15)284) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:child_process:826
    err = new Error(msg);
          ^

Error: Command failed: git remote add -f destination https://github.ABC.com/salesforce/ABC-Salesforce-POC.git
error: remote destination already exists.

**Comment by mitchspano** [comment]
Thanks for checking out the action. Please share your repository's workflow YML so I can assist with debugging.

**Comment by devboorla** [comment]
- name: Run SFDX Scanner - Report findings as comments
      uses: mitchspano/sfdx-scan-pull-request@v0.1.10
      with:
        pmdconfig: .github/workflows/pmd-ruleset.xml
        severity-threshold: 4
        strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by mitchspano** [comment]
Can you share the entire file? I would like to see how the checkout action is being performed.

**Comment by mitchspano** [comment]
Is this being ran on a standalone repository or on a fork of an existing repository?

**Comment by devboorla** [comment]
fork of an existing repo. Whenever a PR is created the action is being called upon. checkout and all happens properly as I am running validation against target org successfully.  I unfortunately cannot share code as it is for an enterprise. but below is the action that I use to do checkout. pretty standard stuff. nothing out of ordinary.

  build:
    runs-on: Java
    steps:
    - uses: actions/checkout@v2
....
....
....
 - name: Install Salesforce CLI
      run: |
        node_modules/sfdx-cli/bin/run plugins:install @salesforce/sfdx-scanner

**Comment by mitchspano** [comment]
Gotcha - thank your for clarifying.

The code in question is [here](https://github.com/mitchspano/sfdx-scan-pull-request/blob/main/src/git-actions.ts#L36).
It was introduced in #24 as part of a fix for #23. I am curious why that seemed to resolve the issue then, but it is causing errors now....

To test this out, I have removed the registration of the `destination` remote in [this commit](https://github.com/mitchspano/sfdx-scan-pull-request/compare/main...fixForkingIssue) on the [fixForkingIssue branch](https://github.com/mitchspano/sfdx-scan-pull-request/tree/fixForkingIssue).

Can you try again with the following yml structure:

```yml
- name: Run SFDX Scanner - Report findings as comments
  uses: mitchspano/sfdx-scan-pull-request@fixForkingIssue
  with:
    pmdconfig: .github/workflows/pmd-ruleset.xml
    severity-threshold: 4
    strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
