### ISSUE TITLE
Scanner breaks when invoked from branch commit/push

### ISSUE THREAD

**Issue by leojok-fluido** [mitchspano/sfdx-scan-pull-request#63]
```
Run mitchspano/sfdx-scan-pull-request@v0.1.12
Beginning sfdx-scan-pull-request run...
Validating that this action was invoked from an acceptable context...
Getting difference within the pull request ... { baseRef: undefined, headRef: undefined }
fatal: ambiguous argument 'destination/undefined...origin/undefined': unknown revision or path not in the working tree.
```

Code index.ts sets pullRequest: context?.payload?.pull_request in line 70,
then line 223 breaks due to pullRequest being null/undefined:
const filePathToChangedLines = await getDiffInPullRequest(
    pullRequest?.base?.ref,
    pullRequest?.head?.ref,
    pullRequest?.base?.repo?.clone_url
  );

GHA yml
```
- name: Run SFDX Scanner
  uses: mitchspano/sfdx-scan-pull-request@v0.1.12
  with:
    pmdconfig: config/pmd-rules.xml
    target: $GITHUB_WORKSPACE/force-app/main/default/classes/*.cls
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Tried different variations of target such as:
- force-app/main/default
- force-app/main/default/classes
- $GITHUB_WORKSPACE/force-app/main/default/classes/*.cls
- $GITHUB_WORKSPACE/force-app/main/default/classes
