### ISSUE TITLE
Error running the scanner github action 

### ISSUE THREAD

**Issue by RaviVaranasi** [mitchspano/sfdx-scan-pull-request#66]
Below is the error running the Github action. We did not change anything in the action.  Did a transitive dependency change. The error indicates we did not get a JSON payload back

```
{
  message: 'Unexpected token T in JSON at position 1',
  status: undefined,
  stack: 'SyntaxError: Unexpected token T in JSON at position 1\n' +
    '    at JSON.parse (<anonymous>)\n' +
    '    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12983\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12738\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at o (/home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12485)\n' +
    '    at cli (/home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12871)\n' +
    '    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:13250\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /home/runner/work/_actions/mitchspano/sfdx-scan-pull-request/v0.1.15/dist/index.js:1:12738',
  output: undefined
}
```

```

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.15
        with:
          pmdconfig: ruleset.xml
          severity-threshold: 3
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
