### ISSUE TITLE
PDM results not populating

### ISSUE THREAD

**Issue by raghu-madireddy** [mitchspano/sfdx-scan-pull-request#73]
for some reason not able to see pmd results and always scanning coming as success. I can see errors on my local. 
 ```
     - name: Run SF scanner
          id: sf_code_scanner
          uses: mitchspano/sfdx-scan-pull-request@v0.1.14
          with:
            pmdconfig: 'pmd/deployRules.xml'
            target: 'packge/package.xml'
            severity-threshold: 1
            engine: 'pmd'  

```
```
Beginning sfdx-scan-pull-request run...
Validating that this action was invoked from an acceptable context...
Getting difference within the pull request ... { baseRef: 'develop', headRef: 'feature/release-test' }
From https://github.com/raghu-madireddy/salesforce-metadata-test
 * [new branch]        develop              -> destination/develop
 * [new branch]        feature/release-test -> destination/feature/release-test
 * [new branch]        main                 -> destination/main
(node:2683) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Performing static code analysis on all of the files in the difference...
npx sfdx scanner:run --engine pmd --pmdconfig pmd/deployRules.xml --target ".github/workflows/ci.yml,.github/workflows/initial-checks.yml,.github/workflows/validate-develop.yml,.gitignore,force-app/main/default/classes/TestingReleasePMDTest.cls" --json
Filtering the findings to just the lines which are part of the pull request...
Creating Check Runs using GitHub REST API...
```
