### ISSUE TITLE
ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING type error 

### ISSUE THREAD

**Issue by ghost** [mitchspano/sfdx-scan-pull-request#86]
Hi, I am trying to install and run this package on my repo in my GH actions workflow.
I keep getting the following error and I was wondering if it is something related to the latest versions of either this package or sfdx Code Analyzer.
The error seems likely due to incompatibility with ESL lint.

tried so far:
- using the newest sf commands instead of sfdx but that seems not supported yet
- not specifying Node version and getting unsupported version error
- using a different(classic) token where I only give full access to private repo 
- adding pmdconfig: masterRuleset.xml and adding that file in my repo

<img width="1398" alt="Screenshot 2024-12-10 at 14 42 54" src="https://github.com/user-attachments/assets/a4945de3-959d-4e60-ae43-53d9484b42f4">
<img width="1329" alt="Screenshot 2024-12-10 at 14 43 31" src="https://github.com/user-attachments/assets/adff2df8-b204-4d5e-9156-84009fcfee55">

this is my current yml

```
name: Static Analysis
on:
  pull_request:
    branches: 
      - actionsLinter

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner@latest

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.16
        with:
          pmdconfig: masterRuleset.xml
          severity-threshold: 4
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Debug API Response
        run: echo "${{ steps.scan.outputs.check_run }}"
                  
```

please let me know if this could be an issue for the Code Analyzer instead.

**Comment by mitchspano** [comment]
I think this is a node version thing. I believe the action runner comes with node 18 installed. Try omitting the setup node step and let me know if the problem persists.

**Comment by ghost** [comment]
> I think this is a node version thing. I believe the action runner comes with node 18 installed. Try omitting the setup node step and let me know if the problem persists.

Thanks for the sweep reply. I initially had no node setup step specifying the version and the error was the following:
_The engine "node" is incompatible with this module. Expected version ">=20.0.0". Got "18.20.5"_

<img width="969" alt="Screenshot 2024-12-10 at 16 40 53" src="https://github.com/user-attachments/assets/a931c85d-39db-4ce7-b375-cd23e30034d3">

```
name: Static Analysis
on:
  pull_request:
    branches: 
      - actionsLinter

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner@latest

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v0.1.16
        with:
          pmdconfig: masterRuleset.xml
          severity-threshold: 4
          strictly-enforced-rules: '[{ "engine": "pmd", "category": "Performance", "rule": "AvoidDebugStatements" }]'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Debug API Response
        run: echo "${{ steps.scan.outputs.check_run }}"
                  
```
